### ISSUE TITLE
Tests not working in VS runner.

### ISSUE THREAD

**Issue by JohanLarsson** [GuOrg/Gu.Wpf.UiAutomation#59]
```
Test Name:	DetectsLanguages
Test FullName:	Gu.Wpf.Localization.UiTests.TranslatesFodyProject.DetectsLanguages
Test Source:	C:\Git\Gu.Localization\Gu.Wpf.Localization.UiTests\TranslatesFodyProject.cs : line 16
Test Outcome:	Failed
Test Duration:	0:00:00,035

Result StackTrace:	
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Gu.Wpf.UiAutomation.Application.<>c.<FindExeOrDefault>g__Create|57_0(String fileName)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Gu.Wpf.UiAutomation.Application.FindExeOrDefault(String exeFileName, String default)
   at Gu.Wpf.UiAutomation.Application.AttachOrLaunch(String exeFileName, OnDispose onDispose)
   at Gu.Wpf.Localization.UiTests.TranslatesFodyProject.DetectsLanguages() in C:\Git\Gu.Localization\Gu.Wpf.Localization.UiTests\TranslatesFodyProject.cs:line 18
Result Message:	System.UnauthorizedAccessException : Access to the path 'C:\windows\system32\com\dmp' is denied.
```

**Comment by JohanLarsson** [comment]
https://github.com/GuOrg/Gu.Wpf.UiAutomation/pull/60
